# Generated by Django 4.1.1 on 2022-09-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='volume',
            field=models.CharField(max_length=20),
        ),
    ]
